# Generated by Django 3.1.2 on 2021-01-13 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance_digitalization_app', '0002_auto_20210103_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newdirinline',
            name='current_status',
            field=models.CharField(blank=True, choices=[('1', 'Pending'), ('2', 'Responded')], max_length=120, null=True),
        ),
    ]
