# Generated by Django 3.1.4 on 2021-01-18 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance_digitalization_app', '0003_auto_20210112_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='newdirinline',
            name='completion_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
