# Generated by Django 3.1.4 on 2021-01-20 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compliance_digitalization_app', '0004_newdirinline_completion_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newdirectivecirculationinlineinformation',
            name='assessment_frequency',
        ),
        migrations.RemoveField(
            model_name='newdirinline',
            name='completion_date',
        ),
    ]
