# Generated by Django 3.1.4 on 2021-01-20 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compliance_digitalization_app', '0005_auto_20210120_1538'),
        ('compliance_digitalization_app', '0004_newdirinline_implementation_date'),
    ]

    operations = [
    ]
